"""PR-AMORT P1 / P3' -- train one arm and publish its board.

    P1       tower -> grid codes -> w(71) -> frozen Phi-71 + guided upsample
    P3prime  tower -> field           -> guided upsample          (no Phi)

Same data, same conditioning, same loss, same criteria; the only difference is
whether the Phi-71 intermediate layer sits in the feed-forward path.  That is
the question the pair exists to answer, and it is open precisely because E5
proved Phi-71 is *not* a bottleneck (it reproduces any field it is handed) --
which says nothing about whether it helps a network that has to *produce* one.

The VLM is frozen throughout and runs once per micro-batch, yielding F_pre, the
merger output and H_where together (protocol 2.3).
"""

from __future__ import annotations

import argparse
import json
import math
import subprocess
import time
from dataclasses import asdict
from pathlib import Path
from typing import Any

import numpy as np
import torch


def _provenance() -> dict:
    """Commit **and** working-tree state.

    Recording a bare HEAD would be misleading here: the arm's own source is not
    committed, so HEAD does not describe the code that ran.  The dirty flag, the
    changed-file list and a content hash of the amort package make the run
    reproducible from the artefact rather than from an assumption.
    """
    repo = "/home/bc/VeraRetouch"
    out = {"git_commit": "unknown", "working_tree_dirty": None,
           "changed_files": [], "amort_source_sha256": None}
    try:
        out["git_commit"] = subprocess.check_output(
            ["git", "rev-parse", "HEAD"], cwd=repo).decode().strip()
        st = subprocess.check_output(["git", "status", "--porcelain"],
                                     cwd=repo).decode().strip()
        out["working_tree_dirty"] = bool(st)
        out["changed_files"] = [ln[3:] for ln in st.splitlines()][:80]
    except Exception:
        pass
    try:
        import hashlib

        h = hashlib.sha256()
        for f in sorted(Path(repo, "q3vl/whereb/amort").rglob("*.py")):
            h.update(f.read_bytes())
        for extra in ("q3vl/where/fpre.py", "q3vl/whereb/hiddens.py",
                      "q3vl/whereb/scripts/run_amort_arm.py"):
            h.update(Path(repo, extra).read_bytes())
        out["amort_source_sha256"] = h.hexdigest()
    except Exception:
        pass
    return out


def _git_commit() -> str:
    return _provenance()["git_commit"]


def _first_step_row(path: Path) -> dict | None:
    """The FIRST row of ``steps.jsonl`` -- the deep-supervision witness.

    Returns ``None`` when the file is absent or empty (a run that never took a
    step); `assert_criteria_ran` turns that into the failure, so a missing log
    can never read as a passing check.
    """
    try:
        with Path(path).open(encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if line:
                    return json.loads(line)
    except (OSError, ValueError):
        return None
    return None


def _genctx_checkpoint(store) -> str | None:
    """The ``checkpoint`` field the generated-context cache was produced with.

    ``gencontext.build_record`` stamps it on every record
    (``q3vl/whereb/gencontext.py:122, 168``); the six EPR-018..023 proposals all
    require it to equal the base the arm is running on, because a v2seg readout
    replayed through a cache generated by checkpoint-4976 would be a different
    experiment with an identical-looking board.
    """
    if store is None:
        return None
    for rec in store.iter_records():
        return rec.get("checkpoint")
    return None


#: the ``--train-context`` values that actually draw generated text.  ``mixed``
#: takes ``1 - teacher_fraction`` of every batch from the cache
#: (``trainer.py:535-538``); the ceiling rows (``gt`` / ``shuffled`` /
#: ``fixed_phrase``) never touch it.
GENERATED_TRAIN_CONTEXTS = ("mixed", "generated")


def genctx_dir_of(args) -> Path:
    """``--genctx-dir`` or, when it was not given, ``config.GENCTX_DIR``.

    The flag exists so a base whose cache was regenerated somewhere else (the
    v2seg genwhere re-run lands on local disk, not in the read-only campaign
    root) is pointed at from the command line instead of by editing
    ``q3vl/whereb/config.py`` -- an edit that would silently re-target every
    live arm's re-run at the same time.
    """
    from q3vl.whereb.config import GENCTX_DIR

    return Path(args.genctx_dir) if getattr(args, "genctx_dir", None) else Path(GENCTX_DIR)


def genctx_is_required(args) -> bool:
    """True when this run's TRAINING context cannot be built without the cache.

    New arms only: the live four have re-runs on disk that were produced under
    the old warn-and-fall-back behaviour and have to stay reproducible.
    """
    from q3vl.whereb.amort.arms import NEW_ARMS

    return (getattr(args, "arm", None) in NEW_ARMS
            and getattr(args, "train_context", "mixed") in GENERATED_TRAIN_CONTEXTS
            and not getattr(args, "eval_only", False))


def open_genctx(store_cls, root: Path, split: str, *, args, required: bool):
    """``root/split`` as a :class:`GenContextStore`, or ``None`` / ``SystemExit``.

    The old code warned and returned ``None`` in every case.  Downstream that
    is not a degraded run, it is a DIFFERENT one: ``trainer.py:411-413`` sets
    ``gen_mode = "gt"``, so a ``mixed`` arm trains on 100% teacher text while
    the board records ``train_generated_context: "gt"`` in a field nobody
    diffs against the other arms.  For the six new arms that substitution is
    refused outright.
    """
    path = Path(root) / split
    try:
        st = store_cls(path)
        print(f"genctx {split}: {len(st.rows)} rows  ({path})", flush=True)
        return st
    except Exception as exc:  # noqa: BLE001
        if required:
            raise SystemExit(
                f"arm {getattr(args, 'arm', '?')}: --train-context "
                f"{getattr(args, 'train_context', '?')} needs the generated "
                f"<where> cache for split {split!r} and {path} could not be "
                f"opened ({type(exc).__name__}: {exc}).\n"
                "The old behaviour was a WARN and a silent fall back to 100% "
                "teacher text (trainer.py:411-413, recorded as "
                "train_generated_context='gt') -- a different training "
                "condition from the one the six proposals pre-register and "
                "from the live P1/P3'/UNIQ arms.\n"
                "Fix it with --genctx-dir <root regenerated against this "
                "base>, or pass --train-context gt to run the teacher-only "
                "row on purpose.") from exc
        print(f"WARN no genctx for {split} under {root}: {exc}", flush=True)
        return None


def _loss_preregistration(args, weights, model) -> dict[str, Any]:
    """What ``config/loss_preregistration.json`` says for THIS run.

    The live arms (P1 / P3' / SHAPE3 / UNIQ) publish the seven-term ST_LANG
    stack.  The six EPR-018..023 arms never enter it (``trainer.py:244-251``
    routes them to their own ``compute_loss``), and three of them optimise
    dice -- SEGSAM 0.5, SAMDEC 1.0, CONDINST 1.0 -- so writing the live arms'
    record (``dice_as_target: false``) on a new-arm run is a FALSE
    pre-registration of the thing the batch's red-line waiver is about.  The
    arm's own module is asked instead, and a new arm that cannot answer does
    not start.
    """
    from q3vl.whereb.amort import arms as _arms

    base = {"seed": args.seed, "provenance": _provenance()}
    if getattr(model, "is_new_arm", False):
        hook = _arms.arm_hook(args.arm, "loss_preregistration")
        if hook is None:
            raise SystemExit(
                f"arm {args.arm} has no loss_preregistration() hook, so this run "
                "would publish the LIVE arms' seven-term record (with "
                "dice_as_target: false) as its own pre-registration.  Add\n"
                f"    def loss_preregistration(args=None) -> dict\n"
                f"to {_arms.ARM_MODULES[args.arm]} (see arms.py, "
                "RUN_REQUIRED_HOOKS).")
        rec = dict(hook(args))
        rec.setdefault("arm", args.arm)
        for key in ("iou_as_field_target", "iou_as_selection_target",
                    "dice_as_target"):
            if key not in rec:
                raise SystemExit(
                    f"arm {args.arm}: loss_preregistration() omits {key!r}; all "
                    "three facts are pre-registered per arm and none of them "
                    "may be left to a default.")
        return {**rec, **base,
                "live_arm_seven_term_stack": "not entered by this arm"}
    return {**{"arm": args.arm,
               "weights": weights.to_dict(),
               "form": "L = bce*BCE_soft + sdf*SDF_boundary + area*area_band"
                       " + fake*empty_mask + sep*paired_separation",
               "separation": "relu(margin - (d(m,gt_partner) - d(m,gt_own)))",
               "antonym": "reported only; never a loss term (E3 erratum)",
               # The red line is "IoU is never an OPTIMISATION TARGET FOR THE
               # FIELD".  EPR-012 regresses the selection head's score onto
               # each query's real top-k IoU (a no_grad constant), so a single
               # `iou_as_target: False` would be a false record the moment
               # `uniq_iou > 0` -- the two facts are split so neither can hide
               # behind the other.
               "iou_as_field_target": False,
               "iou_as_selection_target": bool(weights.uniq_iou),
               "dice_as_target": False},
            **base}


def _assert_genctx_checkpoint(args, genctx_train, genctx_eval) -> None:
    """Refuse to start when the cache and the base disagree (EPR-018..023)."""
    want = str(args.checkpoint).rstrip("/")
    for name, store in (("train", genctx_train), ("eval", genctx_eval)):
        got = _genctx_checkpoint(store)
        if got is None:
            continue
        if str(got).rstrip("/") != want:
            raise SystemExit(
                f"genwhere cache for {name} was generated with checkpoint "
                f"{got!r} but this run's base is {want!r}.  Regenerate the "
                "cache (q3vl/whereb/scripts/make_generated_context.py) or run "
                "on the matching base; a readout replayed through a cache from "
                "another base is a different experiment.")


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    from q3vl.where.calibrate import SCHEDULER_KINDS
    from q3vl.whereb.amort.arms import NEW_ARMS
    from q3vl.whereb.readout import READOUT_KINDS

    ap.add_argument("--arm", required=True,
                    choices=["P1", "P3prime", "SHAPE3", "UNIQ", *NEW_ARMS])
    ap.add_argument("--checkpoint",
                    default="/home/bc/data/runs/q3vl_base_sft_20260804/checkpoint-4976")
    ap.add_argument("--basis", default="BA-3-Joint")
    ap.add_argument("--readout", default="band")
    ap.add_argument("--train-split", default="train")
    ap.add_argument("--eval-split", default="V_where")
    ap.add_argument("--device", default="cuda:0")
    ap.add_argument("--attn", default="eager",
                    help="the similarity-field norm is only valid under the "
                         "kernel it was fitted with; see simfield.SimFieldNorm")
    ap.add_argument("--dtype", default="bfloat16")
    ap.add_argument("--out-root", default="/home/bc/data/runs/where_b")
    ap.add_argument("--run-name", default=None)
    ap.add_argument("--micro-batch", type=int, default=8)
    ap.add_argument("--effective-batch", type=int, default=32)
    ap.add_argument("--lr", type=float, default=3e-4)
    ap.add_argument("--epochs", type=float, default=1.0)
    ap.add_argument("--max-hours", type=float, default=3.6)
    ap.add_argument("--max-steps", type=int, default=1200,
                    help="review U4: the A/B is matched on STEPS, not wall clock; "
                         "both arms must use the same value")
    ap.add_argument("--eval-steps", type=int, default=500)
    ap.add_argument("--save-steps", type=int, default=500)
    ap.add_argument("--seed", type=int, default=20260810)
    ap.add_argument("--train-limit", type=int, default=None)
    ap.add_argument("--eval-limit", type=int, default=None)
    ap.add_argument("--norm-samples", type=int, default=256)
    ap.add_argument("--teacher-fraction", type=float, default=0.5)
    # ablation switches (pre-registered rows; the main arm uses the defaults)
    ap.add_argument("--no-sim-field", action="store_true")
    ap.add_argument("--center-prior-channel", action="store_true")
    ap.add_argument("--no-film", action="store_true")
    ap.add_argument("--geom-inject", action="store_true",
                    help="B2: concat the parsed <where> geometry code as "
                         "broadcast spatial channels (bypasses the pooled path)")
    ap.add_argument("--geom-shuffle", action="store_true",
                    help="B2 negative control: permute the geometry slots, "
                         "preserving the active-bit count")
    ap.add_argument("--geom-source", default="parsed",
                    choices=["parsed", "vrmeta", "construction"],
                    help="parsed = generated <where> text (~82%%); vrmeta = "
                         "DEPRECATED residual GT (shape only in practice: "
                         "`region` is 82%% the constant \"center\" and there is "
                         "no extent); construction = AMD-8 GT read off the "
                         "geometry parameters the reasoning template read")
    ap.add_argument("--geom-db", default=None,
                    help="sqlite sidecar for --geom-source construction "
                         "(default config.CONSTRUCT_GEOM_DB); build it with "
                         "scripts/export_construct_geometry.py")
    ap.add_argument("--geom-mode", default="broadcast", choices=["broadcast", "pch"],
                    help="broadcast = 21 constant channels on the stem (lower "
                         "bound form, NOT resumable); pch = zero-initialised "
                         "prototype/cross-attention residual on the tower's "
                         "penultimate features (proposal D-1, resumable)")
    ap.add_argument("--pch-size", default="full", choices=["full", "lite"],
                    help="PCH capacity档: full ~3.9M, lite ~0.5M (G6 ablation)")
    ap.add_argument("--pch-impl", default="v0", choices=["v0", "spec"],
                    help="v0 = the simplified module EPR-001/002/003/007/008 ran "
                         "(AMD-2: frozen, it is their control series); spec = the "
                         "proposal §2.2 module (AMD-4: what the M series runs on)")
    # --- M series (proposal §2.5).  Defaults keep every existing command line
    # byte-identical in behaviour: no --m-arm means no harness at all.
    ap.add_argument("--m-arm", default=None,
                    help="M0 / M1-full / M1-lite / M1-prob / M2 / M2b / M3 / M4 / M5")
    ap.add_argument("--code-source", default="construction",
                    choices=["construction", "file", "vrmeta", "parsed"],
                    help="construction = AMD-8 GT code from the exported geometry "
                         "sidecar; file = a codes.jsonl (an extraction arm's "
                         "output, or AMD-1's zero-shot reference column); vrmeta "
                         "= the AMD-8-superseded residual code, for reproducing "
                         "the v0 series only")
    ap.add_argument("--code-file", default=None,
                    help="codes.jsonl keyed by sample_id (--code-source file)")
    ap.add_argument("--m-conf", type=float, default=1.0,
                    help="M4: the conf multiplier for this row")
    ap.add_argument("--m-group", default="shape",
                    choices=["shape", "dir", "ext", "cont"],
                    help="M5: the single group left un-nulled")
    ap.add_argument("--m-seed", type=int, default=20260812,
                    help="seed for the derangement / Beta conf draws / dropout")
    ap.add_argument("--cond-dropout", type=float, default=None,
                    help="§2.4 all-group conditioning dropout (default 0.15 when "
                         "an M arm trains)")
    ap.add_argument("--cond-dropout-group", type=float, default=None,
                    help="§2.4 per-group conditioning dropout (default 0.05)")
    ap.add_argument("--recipe", default=None, choices=[None, "m-series"],
                    help="m-series = apply §2.4 verbatim (AdamW 3e-4 / wd 1e-4 / "
                         "cosine / warmup 300 / batch 64 / 10k steps)")
    ap.add_argument("--freeze-base", action="store_true",
                    help="train ONLY the injector (proposal §2.4).  This is what "
                         "makes M0 exactly the resumed checkpoint's own board: "
                         "with the backbone frozen no part of Delta can be "
                         "continued training rather than injection")
    ap.add_argument("--pooled-w", action="store_true",
                    help="registered control arm: pool to one vector before w(71)")
    ap.add_argument("--sdf-weight", type=float, default=None,
                    help="P2 shaped-weight recalibration (pre-registered default 0.10)")
    ap.add_argument("--area-weight", type=float, default=None,
                    help="P2 shaped-weight recalibration (pre-registered default 0.05)")
    ap.add_argument("--eik-weight", type=float, default=0.0,
                    help="SHAPE3: soft eikonal |grad s|=1 on the s field")
    ap.add_argument("--curv-weight", type=float, default=0.0,
                    help="P2 structural pack: excess-curvature penalty")
    ap.add_argument("--mono-weight", type=float, default=0.0,
                    help="P2 structural pack: monotonicity hinge")
    ap.add_argument("--sep-weight", type=float, default=None,
                    help="override the pre-registered separation weight (0.30)")
    ap.add_argument("--resume", default=None,
                    help="checkpoint to continue from (weights only; a fresh "
                         "schedule is started and recorded as such)")
    ap.add_argument("--eval-only", action="store_true",
                    help="skip training and re-score --resume's checkpoint "
                         "(rebuilds a board that was missing a criterion)")
    ap.add_argument("--no-semantic-head", action="store_true")
    # --- EPR-018..023 shared flags -----------------------------------------
    # NOTE the name: `--readout` above is the P1 field readout (band/...), which
    # predates these arms by a campaign.  The six proposals write `--readout
    # seg_where`; on this entry that flag is spelled `--cond-readout`, and the
    # two `--readout-{qtok,nseg}` names are as written.
    ap.add_argument("--cond-readout", default="seg_where",
                    choices=list(READOUT_KINDS),
                    help="EPR-018..023: WHERE the language condition h_cond is "
                         "read from (q3vl/whereb/readout.py). Only consumed by "
                         "the six new arms.")
    ap.add_argument("--readout-qtok", type=int, default=0,
                    help="K_q for --cond-readout qtok (ablation rows 1/4/8)")
    ap.add_argument("--readout-nseg", type=int, default=1,
                    help="K for --cond-readout seg_where; K>1 needs an SFT "
                         "variant that supervises K seg tokens (placeholder)")
    ap.add_argument("--readout-on-missing-tag", default="last",
                    choices=["last", "raise"],
                    help="generated format failures (no closing tag): read the "
                         "last row of the span and COUNT it, or refuse")
    ap.add_argument("--newarm-legacy-routing", action="store_true",
                    help="EPR-018..023 alternative row: keep the old semantic "
                         "routing (SemanticHead built, semantic family does NOT "
                         "go through the new head). Default = B-4: all four "
                         "families through the new head.")
    ap.add_argument("--pixgt-source", default="render",
                    choices=["render", "cgt1024", "maskhi"],
                    help="pixel-GT source for the new arms: analytic re-render "
                         "(semantic falls back and is counted), .cgt.png at "
                         "short side 1024, or the published .maskhi.png at 512")
    ap.add_argument("--pixgt-fallback", default="maskhi512",
                    choices=["maskhi512", "cgt1024"],
                    help="which raster the semantic family / geometry misses "
                         "fall back to")
    ap.add_argument("--no-pixgt", action="store_true",
                    help="do not build a pixel-GT provider (an arm that "
                         "supervises on the (gh,gw) grid only)")
    # generic optimiser/schedule overrides.  Every default here is the value
    # AmortTrainConfig already carries, so nothing changes unless one is passed.
    ap.add_argument("--weight-decay", type=float, default=0.01)
    ap.add_argument("--scheduler", default="cosine",
                    choices=list(SCHEDULER_KINDS))
    ap.add_argument("--warmup-ratio", type=float, default=0.03)
    ap.add_argument("--max-grad-norm", type=float, default=1.0,
                    help="0 or negative = clipping OFF (PointRend / LIIF / "
                         "CondInst); the gnorm column is still logged")
    ap.add_argument("--want-hi", action="store_true",
                    help="carry gt_hi / guide_hi at the spec-5 resolution into "
                         "the batch and the training loss (PointRend needs it)")
    # --- UNIQ arm (EPR-011): unified query head -----------------------------
    ap.add_argument("--uniq-k", type=int, default=4,
                    help="UNIQ: number of query slots (hypotheses)")
    ap.add_argument("--uniq-fourier-bands", type=int, default=0,
                    help="UNIQ arm A: random-Fourier coordinate basis bands "
                         "(0 = no coordinate channels, the DELTA S5.6-"
                         "compliant arm B); pre-registered M3 guard column is "
                         "the execution line for the basis arm")
    ap.add_argument("--uniq-fourier-scale", type=float, default=1.0,
                    help="UNIQ: Fourier bandwidth (Tancik's calibration knob)")
    ap.add_argument("--uniq-cls-weight", type=float, default=0.05,
                    help="UNIQ: winner family-class CE weight")
    ap.add_argument("--uniq-sel-weight", type=float, default=0.05,
                    help="UNIQ: selection-head distillation CE weight")
    # --- EPR-012: IoU regression selection head (all default off) -----------
    ap.add_argument("--uniq-iou-head", action="store_true",
                    help="EPR-012: swap the linear selection head for SAM's "
                         "3-layer MLP + sigmoid and regress each query's real "
                         "matched-area top-k IoU (replaces the winner-index CE "
                         "unless --uniq-iou-keep-ce)")
    ap.add_argument("--uniq-iou-weight", type=float, default=0.05,
                    help="EPR-012: weight of the IoU regression term")
    ap.add_argument("--uniq-iou-winner-only", action="store_true",
                    help="EPR-012 ablation: SAM v1 form -- regress the winner "
                         "only instead of SAM2's supervise_all_iou")
    ap.add_argument("--uniq-iou-mse", action="store_true",
                    help="EPR-012 ablation: MSE instead of L1")
    ap.add_argument("--uniq-iou-keep-ce", action="store_true",
                    help="EPR-012 ablation: keep 0.05*CE(sel) alongside the "
                         "IoU regression instead of replacing it")
    ap.add_argument("--uniq-iou-stability", type=float, default=0.0,
                    help="EPR-012 ablation: SAM2 inference-only stability "
                         "fallback threshold (0.98 = SAM2 default; 0 = off)")
    # --- EPR-015: relaxed WTA (MHP) ----------------------------------------
    ap.add_argument("--uniq-eps", type=float, default=0.0,
                    help="EPR-015: MHP association relaxation; winner keeps "
                         "1-eps and the K-1 losers share eps (paper: 0.05)")
    ap.add_argument("--uniq-hdrop", type=float, default=0.0,
                    help="EPR-015: hypothesis dropout probability (paper: 0.01)")
    ap.add_argument("--train-context", default="mixed",
                    choices=["mixed", "gt", "shuffled", "fixed_phrase"],
                    help="'shuffled'/'fixed_phrase' are the training-ceiling rows")
    ap.add_argument("--genctx-dir", default=None,
                    help="root of the generated-<where> cache; <root>/<split> is "
                         "opened.  Default = q3vl/whereb/config.py GENCTX_DIR.  "
                         "A base whose cache was regenerated elsewhere (the "
                         "v2seg genwhere re-run) is pointed at with this flag "
                         "instead of by editing config.py -- the checkpoint "
                         "guard below still has to pass.")
    ap.add_argument("--quick-eval-limit", type=int, default=200)
    args = ap.parse_args(argv)

    t_start = time.time()

    # -- M series (§2.5): the arm decides the wiring, not the command line ----
    # Resolved before anything is built so the run record shows one consistent
    # configuration; an arm whose flags and whose name disagree is how EPR-003's
    # controls became unauditable.
    m_spec = None
    if args.m_arm:
        from q3vl.whereb.amort.mseries import TRAIN_RECIPE, arm_spec

        m_spec = arm_spec(args.m_arm)
        args.geom_inject = bool(m_spec.inject)
        if m_spec.inject:
            args.geom_mode = "pch"
            args.pch_impl = "spec"
            if m_spec.pch_size:
                args.pch_size = m_spec.pch_size
        if m_spec.eval_only and not args.eval_only:
            print(f"NOTE {m_spec.name} is an eval-only arm (it reuses M1's "
                  "weights); forcing --eval-only", flush=True)
            args.eval_only = True
        if args.recipe is None:
            args.recipe = "m-series"
        if args.cond_dropout is None:
            args.cond_dropout = TRAIN_RECIPE["cond_dropout_all"]
        if args.cond_dropout_group is None:
            args.cond_dropout_group = TRAIN_RECIPE["cond_dropout_group"]
        print(f"M-SERIES arm={m_spec.name} transform={m_spec.transform} "
              f"eval_only={args.eval_only} pch={args.pch_impl}/{args.pch_size}",
              flush=True)

    # ---------------------------------------------------------------------
    # Raise RLIMIT_NOFILE before anything opens a file.
    # ---------------------------------------------------------------------
    # Queue-run jobs inherit pueued's soft limit of **1024**, while an
    # interactive shell here gets 1048576.  That difference is invisible until
    # it bites: this arm opens sqlite catalogues for 35 dataset batches from
    # several worker threads on top of a loaded VLM and three published stores,
    # and at 1024 it exhausts descriptors -- surfacing as sqlite
    # "unable to open database file" (55,512 lookups) plus Errno 24, i.e. an
    # 83.7% mask-family failure that reproduces *not at all* when the same code
    # is run by hand.  The process genuinely needs the descriptors, so it asks
    # for them rather than tiptoeing around the limit.
    try:
        import resource

        soft, hard = resource.getrlimit(resource.RLIMIT_NOFILE)
        if soft < hard:
            resource.setrlimit(resource.RLIMIT_NOFILE, (hard, hard))
        print(f"RLIMIT_NOFILE {soft} -> {resource.getrlimit(resource.RLIMIT_NOFILE)[0]}",
              flush=True)
    except Exception as exc:  # noqa: BLE001
        print(f"WARN could not raise RLIMIT_NOFILE: {exc}", flush=True)

    from transformers import AutoProcessor

    from q3vl.train.collator import Sft2SegCollator
    from q3vl.train.modeling import load_model
    from q3vl.whereb.amort.data import (AmortBatchBuilder, ForeignIndex,
                                        family_labels)
    from q3vl.whereb.amort.evaluate import evaluate_arm
    from q3vl.whereb.amort.losses import LossWeights
    from q3vl.whereb.amort.model import AmortModel
    from q3vl.whereb.amort.resume import load_resumable
    from q3vl.whereb.amort.simfield import (SimFieldNorm, WordEmbedder,
                                            similarity_field, subject_nouns)
    from q3vl.whereb.amort.trainer import AmortTrainConfig, AmortTrainer
    from q3vl.whereb.context import ShuffleIndex
    from q3vl.whereb.data import open_dataset
    from q3vl.whereb.fields import load_basis
    from q3vl.whereb.hiddens import EncodeItem, FrozenVLM
    from q3vl.whereb.stores import GenContextStore

    run_name = args.run_name or f"amort_{args.arm}"
    run_dir = Path(args.out_root) / run_name
    (run_dir / "config").mkdir(parents=True, exist_ok=True)
    print(f"run_dir {run_dir}", flush=True)

    # -- frozen model ------------------------------------------------------
    proc = AutoProcessor.from_pretrained(args.checkpoint)
    model_vlm = load_model(args.checkpoint, attn_implementation=args.attn,
                           dtype=args.dtype).to(args.device).eval()
    if args.cond_readout == "qtok" and args.arm in NEW_ARMS:
        # the learnable-query readout row: vocabulary extension + embedding
        # forward hook, uniq4's mechanism verbatim (readout.make_readout_vlm)
        from q3vl.whereb.readout import ReadoutSpec, make_readout_vlm

        vlm = make_readout_vlm(model_vlm, proc, device=args.device,
                               spec=ReadoutSpec(kind="qtok",
                                                qtok=args.readout_qtok),
                               want_merger=True)
    else:
        vlm = FrozenVLM(model_vlm, proc, device=args.device, want_merger=True)
    collator = Sft2SegCollator(proc, max_length=2048, system_prompt=None)
    basis = load_basis(args.basis).to(args.device)
    embedder = WordEmbedder.from_checkpoint(args.checkpoint, proc.tokenizer)

    # -- data --------------------------------------------------------------
    # Review U7 / data discipline: `winner_confidence == "low"` must not enter
    # the SFT main training set.  It stays in the EVAL split so the stratum can
    # be reported, but the headline there is normal-only (see evaluate.py).
    train_ds, train_info = open_dataset(args.train_split, need_mask=True,
                                        exclude_low=True)
    eval_ds, eval_info = open_dataset(args.eval_split, need_mask=True)
    tr_rows = train_ds.meta_rows()
    ev_rows = eval_ds.meta_rows()
    # local only; global has zero part in training (registered ruling)
    train_idx = [i for i, r in enumerate(tr_rows) if r.get("render_mode") == "local"]
    eval_idx = [i for i, r in enumerate(ev_rows) if r.get("render_mode") == "local"]
    if args.train_limit:
        train_idx = train_idx[: args.train_limit]
    if args.eval_limit:
        eval_idx = eval_idx[: args.eval_limit]
    print(f"train local {len(train_idx)}  eval local {len(eval_idx)}", flush=True)

    tr_shuffle_rows = train_ds.shuffle_records()
    ev_shuffle_rows = eval_ds.shuffle_records()
    train_shuffle = ShuffleIndex(tr_shuffle_rows, seed=0)
    eval_shuffle = ShuffleIndex(ev_shuffle_rows, seed=0)
    foreign = ForeignIndex(tr_shuffle_rows, seed=args.seed)
    genctx_root = genctx_dir_of(args)
    genctx = open_genctx(GenContextStore, genctx_root, args.eval_split,
                         args=args, required=False)
    genctx_train = open_genctx(GenContextStore, genctx_root, args.train_split,
                               args=args,
                               required=genctx_is_required(args))

    print("fetching mask families (construction-side .vrmeta.json)...", flush=True)
    t0 = time.time()
    fam_train = family_labels(train_ds, train_idx)
    fam_eval = family_labels(eval_ds, eval_idx)
    fam_hist: dict[str, int] = {}
    for v in fam_train.values():
        fam_hist[v] = fam_hist.get(v, 0) + 1
    print(f"  {time.time()-t0:.0f}s  train families {fam_hist}", flush=True)

    id_to_index_tr = {train_ds.record(i)["sample_id"]: i for i in train_idx}
    id_to_index_ev = {eval_ds.record(i)["sample_id"]: i for i in eval_idx}

    # -- fit the arm-wide similarity normalisation -------------------------
    # Arm constants, over every valid cell of a sample of the training split.
    # Never per image (s-cache contract red line).
    print(f"fitting similarity-field norm on {args.norm_samples} samples...", flush=True)
    t0 = time.time()
    rng = np.random.default_rng(args.seed)
    pick = rng.choice(len(train_idx), size=min(args.norm_samples, len(train_idx)),
                      replace=False)
    pool: list[np.ndarray] = []
    for start in range(0, len(pick), 8):
        chunk = [train_idx[int(j)] for j in pick[start:start + 8]]
        samples = [train_ds[i] for i in chunk]
        items = []
        for s in samples:
            from q3vl.whereb.data import _PromptShim

            enc = collator.encode_one(_PromptShim(s, instruction=s.instruction))
            n_p = enc["n_prompt_tokens"]
            items.append(EncodeItem(sample_id=s.sample_id, image=s.image,
                                    prompt_ids=enc["input_ids"][:n_p], where_ids=()))
        for s, e in zip(samples, vlm.encode(items)):
            nouns = subject_nouns(s.where_text or "")
            if not nouns or e.f_merger is None:
                continue
            emb = embedder(nouns[0]).to(e.f_merger.device)
            pool.append(similarity_field(e.f_merger, emb, "dot").cpu().numpy())
    from q3vl.whereb.amort.simfield import fit_norm

    norm = fit_norm(pool, kind="dot", gain=1.0, sigma=1.0,
                    attn_implementation=args.attn, checkpoint=args.checkpoint,
                    n_samples=len(pool))
    print(f"  norm center={norm.center:.4f} scale={norm.scale:.4f} "
          f"domain=[{norm.raw_min:.3f}, {norm.raw_max:.3f}] "
          f"cells={norm.n_cells} ({time.time()-t0:.0f}s)", flush=True)

    # -- model -------------------------------------------------------------
    from q3vl.whereb.amort import arms as _arms

    model = AmortModel(
        args.arm, readout=args.readout,
        new_arm_defaults=not args.newarm_legacy_routing,
        arm_kwargs=dict(_arms.ARM_KWARGS),
        arm_args=(_arms.ARM_ARGS if _arms.ARM_ARGS is not None else args),
        use_sim_field=not args.no_sim_field,
        use_center_prior_channel=args.center_prior_channel,
        with_semantic=not args.no_semantic_head,
        use_film=not args.no_film,
        pooled_w=args.pooled_w,
        geom_inject=args.geom_inject,
        geom_mode=args.geom_mode,
        pch_size=args.pch_size,
        pch_impl=args.pch_impl,
        seed=args.seed,
        uniq_k=args.uniq_k,
        uniq_fourier_bands=args.uniq_fourier_bands,
        uniq_fourier_scale=args.uniq_fourier_scale,
        uniq_iou_head=args.uniq_iou_head,
        uniq_sel_stability=args.uniq_iou_stability,
    ).to(args.device)
    if model.is_new_arm and args.cond_readout == "qtok":
        print(f"readout qtok: {model.attach_readout_vlm(vlm)}", flush=True)
    resume_report: dict[str, Any] = {}
    if args.resume:
        sd = torch.load(args.resume, map_location=args.device)
        resume_report = report = load_resumable(model, sd["model"])
        print(f"resumed weights from {args.resume} (step {sd.get('step')}); "
              "a NEW schedule starts here and run_setup records it", flush=True)
        print(f"  resume: {json.dumps(report)}", flush=True)

    # Structural no-op check, before a single step: the arms resume a trained
    # checkpoint, and a module that perturbs step 0 makes every Delta a mixture
    # of "the injection did something" and "the new tensors moved the model".
    # Only meaningful while the injector is still at its initialisation -- an
    # eval-only arm resuming M1's *trained* injector must not be asserted to be
    # inert, which would be asserting the experiment failed.
    zero_init_check: dict[str, Any] = {"ran": False, "reason": "not applicable"}
    pch_is_fresh = (not args.resume
                    or any(k.startswith("pch.")
                           for k in resume_report.get("from_init", [])))
    if model.pch is not None and args.pch_impl == "spec" and pch_is_fresh:
        from q3vl.whereb.amort.geocode import GeoCode
        from q3vl.whereb.amort.geomparse import GEOM_DIM

        probe = torch.randn(1, model.geo.tower.ch, 4, 5, device=args.device)
        code = GeoCode.from_multihot(
            [1.0 if i in (0, 6, 15) else 0.0 for i in range(GEOM_DIM)],
            c_cont=[0.5, 0.5, 0.3])
        zero_init_check = {"ran": True,
                           **model.pch.assert_zero_at_init(probe, code.to(args.device))}
        model.pch.reset_domain()
        print(f"PCH zero-init check {json.dumps(zero_init_check)}", flush=True)
    if args.freeze_base:
        for name, p in model.named_parameters():
            p.requires_grad = name.startswith("pch.")
        n_pch = sum(p.numel() for n, p in model.named_parameters()
                    if n.startswith("pch."))
        if not n_pch:
            raise SystemExit("--freeze-base with no injector: nothing would train")
        print(f"FROZEN BASE: only the injector trains ({n_pch:,} params); "
              "M0 is therefore the resumed checkpoint itself", flush=True)
    print(f"trainable params {model.n_trainable():,}", flush=True)

    _kw = {}
    if args.sep_weight is not None:
        _kw["sep"] = float(args.sep_weight)
    if args.curv_weight:
        _kw["curv"] = float(args.curv_weight)
    if args.mono_weight:
        _kw["mono"] = float(args.mono_weight)
    if args.eik_weight:
        _kw["eik"] = float(args.eik_weight)
    if args.sdf_weight is not None:
        _kw["sdf"] = float(args.sdf_weight)
    if args.area_weight is not None:
        _kw["area"] = float(args.area_weight)
    if args.arm == "UNIQ":
        _kw["uniq_cls"] = float(args.uniq_cls_weight)
        _kw["uniq_sel"] = float(args.uniq_sel_weight)
        if args.uniq_iou_head:
            # EPR-012: the IoU regression REPLACES the winner-index CE unless
            # the ablation flag asks for both in parallel.
            _kw["uniq_iou"] = float(args.uniq_iou_weight)
            _kw["uniq_iou_winner_only"] = bool(args.uniq_iou_winner_only)
            _kw["uniq_iou_mse"] = bool(args.uniq_iou_mse)
            if not args.uniq_iou_keep_ce:
                _kw["uniq_sel"] = 0.0
        if args.uniq_eps:                       # EPR-015
            _kw["uniq_eps"] = float(args.uniq_eps)
        if args.uniq_hdrop:
            _kw["uniq_hdrop"] = float(args.uniq_hdrop)
    weights_pre = LossWeights(**_kw)
    common = dict(embedder=embedder, norm=norm, device=args.device,
                  attn_implementation=args.attn, checkpoint=args.checkpoint,
                  use_center_prior_channel=args.center_prior_channel,
                  # review U1: the pair guard must use the same margin the hinge
                  # does, or it would reject the wrong set of pairs
                  sep_margin=weights_pre.sep_margin,
                  geom_inject=args.geom_inject,
                  geom_shuffle=args.geom_shuffle,
                  geom_source=args.geom_source,
                  geom_db=args.geom_db)
    # --- EPR-018..023 builder seams (absent for every live arm) ------------
    newarm_kw_tr: dict[str, Any] = {}
    newarm_kw_ev: dict[str, Any] = {}
    if model.is_new_arm:
        from q3vl.whereb.amort.arms import arm_hook
        from q3vl.whereb.amort.pixgt import PixGTProvider
        from q3vl.whereb.readout import (ReadoutBuilder, ReadoutSpec,
                                         color_texts_of)

        ro_spec = ReadoutSpec(kind=args.cond_readout, qtok=args.readout_qtok,
                              nseg=args.readout_nseg)
        _spec_hook = arm_hook(args.arm, "readout_spec")
        if _spec_hook is not None:
            ro_spec = _spec_hook(args) or ro_spec
        print(f"readout {ro_spec.to_dict()}", flush=True)
        need_color = ro_spec.kind in ("color_close", "im_end", "seg_where", "qtok")
        ctex_tr = ctex_ev = {}
        if need_color:
            t0 = time.time()
            ctex_tr = color_texts_of(train_ds, train_idx)
            ctex_ev = color_texts_of(eval_ds, eval_idx)
            print(f"teacher <color> spans: train {len(ctex_tr)} eval "
                  f"{len(ctex_ev)} ({time.time()-t0:.0f}s)", flush=True)

        def _mk_readout():
            return ReadoutBuilder(collator.tokenizer, ro_spec,
                                  on_missing_tag=args.readout_on_missing_tag)

        newarm_kw_tr = {"readout": _mk_readout(), "color_texts": ctex_tr}
        newarm_kw_ev = {"readout": _mk_readout(), "color_texts": ctex_ev}
        # the arm's own builder overrides (e.g. PointRend's want_hi=True, or a
        # per-arm `pixgt_size`); applied whether or not a provider is built
        _bkw = arm_hook(args.arm, "builder_kwargs")
        _extra = dict(_bkw(args) or {}) if _bkw is not None else {}
        pix_size = _extra.pop("pixgt_size", None)
        if args.want_hi:
            _extra.setdefault("want_hi", True)
        if not args.no_pixgt:
            from q3vl.whereb.amort.data import ConstructGeomStore
            from q3vl.whereb.config import CONSTRUCT_GEOM_DB

            gstore = ConstructGeomStore(args.geom_db or CONSTRUCT_GEOM_DB)
            for kw, ds, fams in ((newarm_kw_tr, train_ds, fam_train),
                                 (newarm_kw_ev, eval_ds, fam_eval)):
                kw["pixgt"] = PixGTProvider(
                    geom_store=gstore, families=fams,
                    mask_resolver=getattr(ds, "mask_resolver", None),
                    maskviews=getattr(ds, "maskviews", None),
                    prefer=args.pixgt_source,
                    raster_fallback=args.pixgt_fallback)
                if pix_size is not None:
                    kw["pixgt_size"] = pix_size
        newarm_kw_tr.update(_extra)
        newarm_kw_ev.update(_extra)
    train_builder = AmortBatchBuilder(
        collator, vlm, basis, shuffle_index=train_shuffle, foreign_index=foreign,
        genctx=genctx_train, families=fam_train, id_to_index=id_to_index_tr,
        dataset=train_ds, **common, **newarm_kw_tr)
    eval_builder = AmortBatchBuilder(
        collator, vlm, basis, shuffle_index=eval_shuffle, foreign_index=None,
        genctx=genctx, families=fam_eval, id_to_index=id_to_index_ev,
        dataset=eval_ds, **common, **newarm_kw_ev)

    # -- M-series code harness ---------------------------------------------
    # The harness owns exactly one thing: the GeoCode each sample is injected
    # with.  Everything else -- images, text, masks, contexts -- stays with the
    # builder, so an M arm cannot accidentally change the data its own baseline
    # was measured on.
    m_harness_train = m_harness_eval = None
    m_pool = None
    if m_spec is not None and m_spec.inject:
        from q3vl.whereb.amort.mseries import (MSeriesHarness, make_code_source,
                                               prepare_pool)

        src_kw = dict(builder=eval_builder, code_file=args.code_file,
                      geometry_db=args.geom_db, dataset=eval_ds,
                      id_to_index=id_to_index_ev)
        eval_source = make_code_source(args.code_source, **src_kw)
        train_source = make_code_source(
            args.code_source, builder=train_builder, code_file=args.code_file,
            geometry_db=args.geom_db, dataset=train_ds,
            id_to_index=id_to_index_tr)
        # arm constants for c_cont, fitted over a sample of the TRAINING codes
        # and never per image (s-cache contract).  The domain stays the
        # contract's [0,1]; the observed range is recorded beside it.
        if args.code_source in ("construction", "file"):
            from q3vl.whereb.amort.geocode import ContNorm

            if pch_is_fresh:
                pick_ids = [train_ds.record(i)["sample_id"]
                            for i in train_idx[: max(1, args.norm_samples)]]
                vals = [train_source.code_for(sid).c_cont.tolist()
                        for sid in pick_ids]
                cont_norm = ContNorm.fit(
                    vals,
                    source=f"{args.code_source} codes, {len(vals)} train samples")
                model.pch.set_cont_norm(cont_norm)
            else:
                # An eval-only arm resumes M1's injector, and the standardisation
                # travelled with it in the checkpoint's buffers.  Refitting here
                # would score the arm on a different input than it trained on --
                # invisibly, because nothing downstream carries the constants.
                cont_norm = ContNorm(
                    mean=tuple(float(x) for x in model.pch.cont_mean),
                    std=tuple(float(x) for x in model.pch.cont_std),
                    fitted=True, source="restored from the resumed checkpoint")
                model.pch.cont_norm = cont_norm
                print("c_cont norm restored from the checkpoint (not refitted)",
                      flush=True)
            eval_source.cont_norm = train_source.cont_norm = cont_norm
            (run_dir / "config" / "cont_norm.json").write_text(
                json.dumps(cont_norm.to_dict(), indent=2), encoding="utf-8")
            print(f"c_cont norm {json.dumps(cont_norm.to_dict())}", flush=True)
        if m_spec.needs_pool:
            ev_ids = [eval_ds.record(i)["sample_id"] for i in eval_idx]
            m_pool = prepare_pool(eval_source, ev_ids)
            print(f"code pool {json.dumps(m_pool.stats())}", flush=True)
        m_harness_eval = MSeriesHarness(
            eval_builder, eval_source, m_spec, train_mode=False,
            seed=args.m_seed, conf_scale=args.m_conf, group=args.m_group,
            pool=m_pool)
        m_harness_train = MSeriesHarness(
            train_builder, train_source, m_spec, train_mode=True,
            seed=args.m_seed + 1, conf_scale=args.m_conf, group=args.m_group,
            pool=m_pool, cond_dropout_all=float(args.cond_dropout or 0.0),
            cond_dropout_group=float(args.cond_dropout_group or 0.0))
        train_builder, eval_builder = m_harness_train, m_harness_eval

    weights = weights_pre
    cfg_kw: dict[str, Any] = dict(
        arm=args.arm, learning_rate=args.lr, effective_batch=args.effective_batch,
        micro_batch=args.micro_batch, epochs=args.epochs, eval_steps=args.eval_steps,
        save_steps=args.save_steps, seed=args.seed, max_hours=args.max_hours,
        teacher_fraction=args.teacher_fraction,
        max_steps=args.max_steps,
        train_context=args.train_context,
        # EPR-018..023: the defaults below are the values AmortTrainConfig
        # already carries, so passing them changes nothing for the live arms.
        weight_decay=args.weight_decay,
        scheduler=args.scheduler,
        warmup_ratio=args.warmup_ratio,
        max_grad_norm=args.max_grad_norm,
    )
    if args.recipe == "m-series":
        from q3vl.whereb.amort.mseries import train_config_kwargs

        steps = int(args.max_steps or 10_000)
        cfg_kw.update(train_config_kwargs(
            max_steps=steps, effective_batch=args.effective_batch))
        # `epochs` bounds the data the loop will draw, and the trainer takes the
        # MINIMUM of that and max_steps.  Leaving it at 1.0 would silently stop a
        # "10k step" arm after one pass -- and stop it at a different point of
        # the cosine than a longer arm, which is the U4 confound.
        need = math.ceil(steps * cfg_kw["effective_batch"] / max(1, len(train_idx)))
        if need > args.epochs:
            print(f"RECIPE §2.4 raises epochs {args.epochs} -> {need} so "
                  f"{steps} steps of batch {cfg_kw['effective_batch']} are "
                  f"reachable over {len(train_idx)} samples", flush=True)
            cfg_kw["epochs"] = float(need)
        print(f"RECIPE §2.4 {json.dumps({k: cfg_kw[k] for k in sorted(cfg_kw)}, default=str)}",
              flush=True)
    cfg = AmortTrainConfig(**cfg_kw)

    # Review N4: quick eval drives `best()` once U3 is wired, so it must not be
    # the set the arm is reported on.  Split V_where local deterministically by
    # sha1(sample_id) -- a rule of the same family as the campaign's splits, not
    # an index prefix -- and select on one half, report the other separately.
    import hashlib

    def _half(i: int) -> int:
        sid = eval_ds.record(i)["sample_id"]
        return int(hashlib.sha1(sid.encode()).hexdigest(), 16) % 2

    sel_idx = [i for i in eval_idx if _half(i) == 0]
    hold_idx = [i for i in eval_idx if _half(i) == 1]
    quick_idx = sel_idx[: args.quick_eval_limit]
    print(f"selection half {len(sel_idx)}  holdout half {len(hold_idx)}", flush=True)

    def quick_eval(step: int) -> dict[str, Any]:
        # `evaluate_arm` puts the model in eval(); `_eval_and_record` swallows
        # exceptions so the arm survives a reporting failure -- which means a
        # raising quick eval used to leave training running in EVAL MODE for the
        # rest of the run.  For EPR-016 that silently deletes the experiment
        # (the auxiliary query rows exist only while `self.training`), and for
        # every arm it changes the forward.  The restore is therefore in a
        # `finally`, not on the success path.
        try:
            board = evaluate_arm(model, eval_builder, eval_ds, quick_idx,
                                 quick=True, batch_size=8)
        finally:
            model.train()
        return {"local_soft_iou_median": board.get("local_soft_iou_median"),
                "gate_pass": board.get("gate_pass"),
                "gate": board.get("gate"),
                "swap_subject_delta": board.get("swap_subject_delta", {}).get("delta"),
                "antonym_median_abs_delta":
                    board.get("antonym_invariance", {}).get("median_abs_delta"),
                "corr_center_minus_gt":
                    board["contexts"]["gt"]["corr_center_minus_corr_gt"]["delta"]
                    if "gt" in board["contexts"] else None}

    # only the TRAINING builder may fall back; the eval builder must keep
    # reporting `uncovered` (review B1)
    train_builder.allow_context_fallback = True
    # EPR-018..023: the six reference recipes each bring their own optimizer and
    # schedule (SGD/AdamW/Adam, linear / multistep / warmup_multistep).  Both
    # hooks are optional; absent = the campaign default, bit-identical.
    opt_spec = sched_kw = None
    if model.is_new_arm:
        from q3vl.whereb.amort.arms import arm_hook

        _os = arm_hook(args.arm, "optimizer_spec")
        opt_spec = _os(args) if _os is not None else None
        _sk = arm_hook(args.arm, "scheduler_kwargs")
        sched_kw = _sk(args, int(args.max_steps or 0)) if _sk is not None else None
        print(f"arm optimizer {opt_spec} scheduler {cfg.scheduler} {sched_kw}",
              flush=True)
    trainer = AmortTrainer(model, train_builder, train_ds, train_idx, cfg, weights,
                           run_dir=run_dir, device=args.device, eval_fn=quick_eval,
                           want_hi=bool(args.want_hi),
                           optimizer_spec=opt_spec, scheduler_kwargs=sched_kw)

    setup = {**trainer.setup(), "provenance": _provenance(),
             "args": vars(args), "train_info": train_info, "eval_info": eval_info,
             "train_family_hist": fam_hist,
             "shuffle_coverage_train": train_shuffle.coverage(),
             "shuffle_coverage_eval": eval_shuffle.coverage(),
             "sim_norm": norm.to_dict(),
             "resumed_from": args.resume,
             "resume_report": resume_report,
             "pch_zero_init_check": zero_init_check,
             "m_series": (None if m_spec is None else
                          {"spec": m_spec.to_dict(),
                           "code_source": args.code_source,
                           "code_file": args.code_file,
                           "geometry_db": args.geom_db,
                           "conf_scale": args.m_conf, "group": args.m_group,
                           "seed": args.m_seed,
                           "recipe": args.recipe,
                           "cond_dropout": args.cond_dropout,
                           "cond_dropout_group": args.cond_dropout_group,
                           "pool": (None if m_pool is None else m_pool.stats())}),
             "vlm": vlm.facts()}
    if model.is_new_arm:
        # EPR-018..023: the readout flag values, the resolved token ids, the
        # base checkpoint and the arm wrapper's own record, frozen with the run
        # (`amort_source_sha256` already covers the new files).
        setup["new_arm"] = {
            "arm": args.arm,
            "readout": train_builder.readout.facts()
            if train_builder.readout is not None else None,
            "gt_pix": train_builder.pixgt.facts()
            if train_builder.pixgt is not None else None,
            "base_checkpoint": args.checkpoint,
            "genctx_dir": str(genctx_root),
            "genctx_dir_source": ("--genctx-dir" if args.genctx_dir
                                  else "q3vl/whereb/config.py GENCTX_DIR"),
            "genctx_present": {"train": genctx_train is not None,
                               "eval": genctx is not None},
            "genctx_checkpoints": {
                "train": _genctx_checkpoint(genctx_train),
                "eval": _genctx_checkpoint(genctx)},
            "b4_all_four_families_through_new_head": model.new_arm_defaults,
            "optimizer_spec": (opt_spec.to_dict() if opt_spec is not None else None),
            "scheduler": {"kind": cfg.scheduler, "kwargs": sched_kw},
            **dict(_arms.ARM_SETUP),
        }
        _assert_genctx_checkpoint(args, genctx_train, genctx)
    (run_dir / "config" / "run_setup.json").write_text(json.dumps(setup, indent=2, default=str),
                                                       encoding="utf-8")
    (run_dir / "config" / "loss_preregistration.json").write_text(
        json.dumps(_loss_preregistration(args, weights, model), indent=2,
                   default=str),
        encoding="utf-8")
    print(json.dumps({k: setup[k] for k in ("arm", "total_optimizer_steps",
                                            "n_train_samples")}), flush=True)

    def _finish_board(board: dict[str, Any]) -> dict[str, Any]:
        """Attach the M-series record and run the pre-registration assertions.

        Deliberately *after* the board exists and *before* it is written: an
        assertion that runs only in a test is an assertion the run can skip, and
        this campaign's recurring failure is a criterion that was defined,
        imported and never called.
        """
        board["pch_zero_init_check"] = zero_init_check
        # EPR-013/014/016: the deep-supervision branches leave no trace except a
        # suffixed `L_*` column, so the head's own facts are checked against the
        # FIRST training step's columns.  `eval_only` re-scores a checkpoint
        # without training, so there is no steps.jsonl of its own to check --
        # recorded as skipped rather than asserted against an absent file.
        from q3vl.whereb.amort.evaluate import assert_criteria_ran

        geo = getattr(model, "geo", None)
        head_facts = geo.facts() if hasattr(geo, "facts") else None
        steps_row = None
        if args.eval_only:
            head_facts = None
            board["deep_supervision_check"] = {"skipped": "eval_only (no "
                                               "training steps in this run)"}
        else:
            first = _first_step_row(run_dir / "steps.jsonl")
            steps_row = first
            board["deep_supervision_check"] = {
                "steps_jsonl": str(run_dir / "steps.jsonl"),
                "first_step": (None if first is None else first.get("step")),
            }
        board["criteria_assertion"] = assert_criteria_ran(
            board, getattr(model, "arm", args.arm),
            head_facts=head_facts, steps_row=steps_row)
        if model.pch is not None and hasattr(model.pch, "domain_report"):
            # §2.4: any "the injection did nothing" claim must show this first
            board["pch_domain_report"] = model.pch.domain_report()
            board["pch_facts"] = model.pch.facts()
            # the fallback claim, checked on the weights that were actually
            # scored rather than on the initialisation: with conf=0 the output
            # must not depend on the code's content
            from q3vl.whereb.amort.geocode import GeoCode

            probe = torch.randn(1, model.geo.tower.ch, 4, 5, device=args.device)
            a = GeoCode.from_multihot([1.0 if i in (0, 6, 15) else 0.0
                                       for i in range(21)],
                                      c_cont=[0.4, 0.6, 0.2]).to(args.device)
            b = GeoCode.from_multihot([1.0 if i in (3, 11, 19) else 0.0
                                       for i in range(21)],
                                      c_cont=[0.9, 0.1, 0.8]).to(args.device)
            board["pch_null_path_check"] = model.pch.assert_null_is_content_free(
                probe, a, b)
        if m_spec is not None and m_harness_eval is None:
            # M0: no code to check, but the baseline every Delta is taken
            # against still has to be quotable under the same convention
            from q3vl.whereb.amort.mseries import assert_board_columns

            board["m_series_assertion"] = {"arm": m_spec.name,
                                           "checks": assert_board_columns(board)}
        if m_harness_eval is not None:
            from q3vl.whereb.amort.mseries import assert_mseries_wired

            board["m_series"] = m_harness_eval.facts().get("m_series")
            board["m_series_assertion"] = assert_mseries_wired(board,
                                                               m_harness_eval)
            if m_harness_train is not None and m_harness_train.n_built:
                board["m_series_train"] = m_harness_train.facts().get("m_series")
            print(f"M-SERIES assertion {json.dumps(board['m_series_assertion'], default=str)}",
                  flush=True)
        return board

    if args.eval_only:
        # Re-score an existing checkpoint without touching its weights.  Used
        # when a board has to be rebuilt because a pre-registered criterion was
        # missing from it -- the arm is NOT retrained, so the numbers stay
        # comparable to the ones already published.
        print("EVAL ONLY: no training; re-scoring the resumed checkpoint",
              flush=True)
        final_dir = run_dir / "eval_final"
        board = evaluate_arm(model, eval_builder, eval_ds, eval_idx,
                             batch_size=8, want_hi=False, out_dir=final_dir,
                             progress=True)
        board["arm"] = args.arm
        board["eval_only"] = True
        board["resumed_from"] = args.resume
        board["builder_facts"] = train_builder.facts()
        board["elapsed_hours"] = round((time.time() - t_start) / 3600.0, 3)
        board = _finish_board(board)
        (final_dir / "metrics.json").write_text(
            json.dumps(board, indent=2, default=str), encoding="utf-8")
        print(json.dumps({
            "eval_only": True,
            "topk_iou_median_normal_only": board.get("topk_iou_median_normal_only"),
            "shape_residual": board.get("criteria_columns", {})
                                   .get("shape_residual", {}).get("median"),
            "shape_residual_gt": board.get("criteria_columns", {})
                                      .get("shape_residual", {})
                                      .get("gt_control", {}).get("median"),
        }), flush=True)
        return 0

    state = trainer.train()

    # -- checkpoint selection (review U3) ----------------------------------
    # Pre-registration: all three hard gates must pass to be selectable, then
    # median top-k IoU decides.  Never a val loss.  If nothing passes, that is
    # the finding -- the arm is reported as having no selectable checkpoint
    # rather than silently delivering whatever the wall clock happened to stop on.
    best = trainer.best()
    selection = {"selected": None, "reason": "", "n_checkpoints": len(state.checkpoints),
                 "n_gate_pass": sum(1 for c in state.checkpoints if c.get("gate_pass"))}
    if best is not None:
        ckpt = run_dir / f"amort_step{best['step']}.pt"
        if not ckpt.exists() and best["step"] == state.step:
            # The last eval record is written at the final step, but the last
            # *save* is named `amort_final.pt` -- `amort_step{final}.pt` only
            # exists when the final step happens to be a multiple of save_steps.
            # Without this the run reports "no selectable checkpoint" even
            # though every checkpoint passed its gates (observed: 3/3 gate-pass,
            # selected None).  Harmless to the numbers here, because the final
            # state and the selected checkpoint are the same weights -- but the
            # record would have understated a passing arm.
            ckpt = run_dir / "amort_final.pt"
        if ckpt.exists():
            model.load_state_dict(torch.load(ckpt, map_location=args.device)["model"])
            selection.update(selected=best["step"], reason="gate_pass + best median top-k IoU",
                             selected_metric=best.get("local_soft_iou_median"))
            print(f"selected checkpoint step{best['step']} "
                  f"(top-k IoU {best.get('local_soft_iou_median')})", flush=True)
        else:
            selection.update(reason=f"gate-passing step{best['step']} but {ckpt} missing")
    else:
        selection.update(reason="NO SELECTABLE CHECKPOINT: no checkpoint passed all "
                                "three pre-registered hard gates")
        print("WARNING no checkpoint passed the hard gates; reporting the final "
              "state and marking the arm as not having cleared its gates", flush=True)

    # -- final board -------------------------------------------------------
    print("final evaluation...", flush=True)
    final_dir = run_dir / "eval_final"
    board = evaluate_arm(model, eval_builder, eval_ds, eval_idx,
                         batch_size=8, want_hi=False, out_dir=final_dir,
                         progress=True)
    board["arm"] = args.arm
    board["checkpoint_selection"] = selection
    board["steps_trained"] = state.step
    board["max_steps_configured"] = args.max_steps
    board["stopped_reason"] = state.stopped_reason
    board["warnings"] = state.warnings
    board["builder_facts"] = train_builder.facts()
    board["elapsed_hours"] = round((time.time() - t_start) / 3600.0, 3)
    board = _finish_board(board)
    try:
        hold = evaluate_arm(model, eval_builder, eval_ds, hold_idx,
                            contexts=("gt", "shuffled"), batch_size=8,
                            want_hi=False)
        hold.pop("_rows", None)
        board["holdout_half"] = {
            "n": len(hold_idx),
            "topk_iou_median": hold.get("topk_iou_median"),
            "gate": hold.get("gate"),
            "note": "sha1-disjoint from the half used for checkpoint selection",
        }
    except Exception as exc:  # noqa: BLE001
        board["holdout_half"] = {"error": f"{type(exc).__name__}: {exc}"}
    rows = board.pop("_rows", {})
    (final_dir / "metrics.json").write_text(json.dumps(board, indent=2, default=str),
                                            encoding="utf-8")
    print(json.dumps({"arm": args.arm,
                      "local_soft_iou_median": board.get("local_soft_iou_median"),
                      "gate": board.get("gate"),
                      "steps": state.step,
                      "hours": board["elapsed_hours"]}, indent=2), flush=True)

    # visualisation (fixed 0..1 colour scale, valid cells only, exact inverse map)
    try:
        from q3vl.whereb.amort.viz import write_panels

        write_panels(model, eval_builder, eval_ds, eval_idx, rows,
                     run_dir / "viz", n_each=6)
    except Exception as exc:  # noqa: BLE001
        print(f"WARN viz failed: {type(exc).__name__}: {exc}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
